repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.3
    hooks:
      - id: terraform_docs
        args:
          - '--args=--hide modules'
          - '--args=--hide providers'
      - id: terraform_fmt
      - id: terraform_tflint
        args:
          - '--args=--module'
      - id: terraform_validate

exclude: examples
