variable "function_name" {
  description = "A unique name for your Lambda Function"
  type        = string
}

variable "code_directory" {
  description = "A relative or full path to the directory with your Lambda Function (and Layer if you use it) code. For example: /opt/lambda"
  type        = string
  default     = null
}

variable "description" {
  description = "Description of what your Lambda Function does"
  type        = string
  default     = "Generated by Terraform"
}

variable "handler" {
  description = "The function entrypoint in your code"
  type        = string
  default     = null
}

variable "runtime" {
  description = "The identifier of the function's runtime"
  type        = string
  default     = null
}

variable "memory_size" {
  description = "The amount of memory in MB your Lambda Function can use at runtime"
  type        = number
  default     = 128
}

variable "timeout" {
  description = "The amount of time your Lambda Function has to run in seconds"
  type        = number
  default     = 3
}

variable "vars" {
  description = "The Lambda environment's configuration settings"
  type        = map(string)
  default     = null
}

variable "tags" {
  description = "A map of tags to assign to the object"
  type        = map(string)
  default     = null
}

variable "subnet_ids" {
  description = "A list of subnet IDs associated with the Lambda function"
  type        = list(string)
  default     = []
}

variable "security_group_ids" {
  description = "A list of security group IDs associated with the Lambda function"
  type        = list(string)
  default     = []
}

variable "cron" {
  description = "The scheduling expression. For example: cron(0 20 * * ? *) or rate(5 minutes)"
  type        = string
}

variable "input" {
  description = "Valid JSON text passed to the target"
  type        = string
  default     = null
}

variable "layer_enabled" {
  description = "Create a Lambda Layer Version resource"
  type        = bool
  default     = false
}

variable "tracing_mode" {
  description = "Define X-Ray tracing mode to record timing and error information for a subset of invocations"
  type        = string
  default     = "PassThrough"
}

variable "package_type" {
  description = "Lambda deployment package type"
  type        = string
  default     = "Zip"
}

variable "image_uri" {
  description = "ECR image URI containing the function's deployment package"
  type        = string
  default     = false
}
