style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/uridium/terraform-aws-lambda-scheduler
options:
  header:
    pattern: "^(.*)$"
    pattern_maps:
      - Subject
